### ISSUE TITLE
DSMapStudio Crash on startup

### ISSUE THREAD

**Issue by humam2104** [soulsmods/DSMapStudio#310] opened 2022-12-31 00:53 UTC
I tried both v1.05, and v1.06. Any help is appreciated

**Comment by kingborehaha** [comment] 2022-12-31 01:00
Have you installed the exact requirements listed in https://github.com/soulsmods/DSMapStudio#system-requirements, Including the one that says "INSTALL THIS IF THE PROGRAM CRASHES ON STARTUP"?

**Comment by humam2104** [comment] 2022-12-31 01:05
I just uninstalled Visual C++, and reinstalled it.. the crashing is still happening.

**Comment by kingborehaha** [comment] 2022-12-31 01:10
Probably restart your computer too, just in case.

If you installed all the requirements (and have a Vulkan compatible GPU) and it still doesn't work after restarting, can you check if DSMapStudio 1.03.1 works?

**Comment by humam2104** [comment] 2022-12-31 01:13
Just restarted, the same problem is happening.
My GPU is 3060 ti. Last time I used the program was on my 980 ti

**Comment by kingborehaha** [comment] 2022-12-31 01:28
Can you check if DSMapStudio 1.03.1 works?

**Comment by humam2104** [comment] 2022-12-31 01:45
It works fine

**Comment by humam2104** [comment] 2022-12-31 02:12
DSMapStudio 1.03.1 works but the others don't... any ideas?

**Comment by kingborehaha** [comment] 2022-12-31 02:29
Can you see if installing https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.12-windows-x64-installer works?

**Comment by kingborehaha** [comment] 2022-12-31 02:50
And if that doesn't work, can you try editing "C:\Users\x\AppData\Local\DSMapStudio\DSMapStudio_Config.json" and changing "EnableSoapstone" to False?

**Comment by humam2104** [comment] 2022-12-31 03:31
I did an hour ago, and I just (repaired) the installation again.. nothing worked.

**Comment by kingborehaha** [comment] 2022-12-31 08:14
You tried EnableSoapstone false, correct?

**Comment by humam2104** [comment] 2023-01-01 14:49
I tried, it still crashes..

**Comment by kingborehaha** [comment] 2023-01-01 19:02
Dang. Can you check windows event viewer to see what pops up when the program fails to launch?

**Comment by Saltyfish-King** [comment] 2023-01-08 03:31
I got the same problem, and went through most of the process you mentioned (DSMapStudio didn't generate DSMapStudio_Config.json for me), but it still crashes on start up - no windows pop up, the application shows up in Task Manager for a little while, then disappears. I'm using a laptop with 1660ti, 16GB RAM.
Here's the info from the event viewer, there're two errors:

The first one is .Net Runtime, it's ID is 1026:
Application: DSMapStudio.exe
CoreCLR Version: 6.0.1222.56807
.NET Version: 6.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at StudioCore.CFG.LoadConfig()
   at StudioCore.CFG.AttemptLoadOrDefault() in D:\a\DSMapStudio\DSMapStudio\StudioCore\CFG.cs:line 142
   at StudioCore.MapStudioNew..ctor() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 87
   at DSMapStudio.Program.Main(String[] args)

The second one (which happens after the first one) is Application Error, it's ID is 1000 (I don't use a English system so sorry for the inconvenience, I will try to translate them in parentheses):
错误应用程序名称 (Faulting application name): DSMapStudio.exe，版本 (Version): 1.3.1.0，时间戳 (Timestamp): 0x6377dc84
错误模块名称 (Faulting module name): KERNELBASE.dll，版本 (Version): 10.0.19041.2364，时间戳 (Timestamp): 0x5b7d4d22
异常代码 (Exception code): 0xe0434352
错误偏移量 (Error Offset): 0x000000000002cd29
错误进程 ID (Faulting process ID): 0x2230
错误应用程序启动时间 (Faulting application startup time): 0x01d9230d78597030
错误应用程序路径 (Faulting Application Path): D:\mods\EldenRing\MODDING\DSMapStudio-1.06\DSMapStudio.exe
错误模块路径 (Faulting module path): C:\WINDOWS\System32\KERNELBASE.dll
报告 ID (Report ID): 781ee4e4-03fa-49aa-8cad-0c3c7e6d6f80
错误程序包全名 (Faulting package full name): 
错误程序包相对应用程序 ID (Application ID relative to the faulty package): 

Hope you find this helpful, and thank you for your great work!

**Comment by humam2104** [comment] 2023-01-08 04:24
Here's my error code from the event viewer:
Details:
`
Application: DSMapStudio.exe CoreCLR Version: 6.0.1222.56807 .NET Version: 6.0.12 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileNotFoundException: Could not find file 'D:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\oo2core_6_win64.dll'. File name: 'D:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\oo2core_6_win64.dll' at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite) at StudioCore.MapStudioNew.AttemptLoadProject(ProjectSettings settings, String filename, Boolean updateRecents, NewProjectOptions options) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 501 at StudioCore.MapStudioNew..ctor() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 160 at DSMapStudio.Program.Main(String[] args) 
`

OK. So I copied the DLL file into the game Directory (because the program couldn't find it) and got another error:
`
---------------------------
DSMapStudio Unhandled Error - 1.06
---------------------------
DSMapStudio has run into an issue.
Crash log has been generated at "D:\Program Files (x86)\DS Tools\DSMapStudio-1.06\Crash Logs\Log 2023-1-08--08-22-03.txt".

Crash Log:
DSMapStudio Version 1.06
One or more errors occurred. (Could not find param file. Functionality will be limited.)

----------------------

Could not find param file. Functionality will be limited.
   at StudioCore.ParamEditor.ParamBank.LoadParamsER(Boolean partial) in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 627

   at StudioCore.ParamEditor.ParamBank.<>c__DisplayClass59_0.<ReloadParams>b__0() in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 732
[Log 2023-1-08--08-22-03.txt](https://github.com/soulsmods/DSMapStudio/files/10367700/Log.2023-1-08--08-22-03.txt)

   at StudioCore.Editor.TaskManager.<>c__DisplayClass4_0.<AddTask>b__0() in D:\a\DSMapStudio\DSMapStudio\StudioCore\Editor\TaskManager.cs:line 56

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
---------------------------
OK   
---------------------------
`

from the Event Viewer, this is the new errors that come up 
`
Application: DSMapStudio.exe CoreCLR Version: 6.0.1222.56807 .NET Version: 6.0.12 Description: The process was terminated due to an unhandled exception. Exception Info: System.AggregateException: One or more errors occurred. (Could not find param file. Functionality will be limited.) ---> System.IO.FileNotFoundException: Could not find param file. Functionality will be limited. at StudioCore.ParamEditor.ParamBank.LoadParamsER(Boolean partial) in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 627 at StudioCore.ParamEditor.ParamBank.<>c__DisplayClass59_0.<ReloadParams>b__0() in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 732 at StudioCore.Editor.TaskManager.<>c__DisplayClass4_0.<AddTask>b__0() in D:\a\DSMapStudio\DSMapStudio\StudioCore\Editor\TaskManager.cs:line 56 at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj) at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of inner exception stack trace --- at StudioCore.Editor.TaskManager.ThrowTaskExceptions() in D:\a\DSMapStudio\DSMapStudio\StudioCore\Editor\TaskManager.cs:line 103 at StudioCore.MapStudioNew.Update(Single deltaseconds) in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 653 at StudioCore.MapStudioNew.Run() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 331 at DSMapStudio.Program.Main(String[] args) 
`
And this one:
`
DSMapStudio.exe 
   1.3.1.0 
   6377dc84 
   KERNELBASE.dll 
   10.0.19041.2364 
   5b7d4d22 
   e0434352 
   000000000002cd29 
   35a4 
   01d92318a3dde59d 
   D:\Program Files (x86)\DS Tools\DSMapStudio-1.06\DSMapStudio.exe 
   C:\WINDOWS\System32\KERNELBASE.dll 
   7e619759-2098-47f4-91da-bcf28d49d662 
`

**Comment by kingborehaha** [comment] 2023-01-08 20:18
@Saltyfish-King
This seems to be a .NET Desktop Runtime issue, which you download at https://aka.ms/dotnet/6.0/windowsdesktop-runtime-win-x64.exe

**Comment by kingborehaha** [comment] 2023-01-08 20:40
@humam2104 Ok, this error seems to indicate your most recent loaded project's targeted game folder ("D:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game") does not have the files it's supposed to, Elden Ring's game folder should already have oo2core_6_win64.dll, and the param file error would be caused by an identical issue. You may want to reinstall Elden Ring.

The REAL issue with this is crashing without warning (and permitting infinite on-load crash loops), those are things I need to look into.

If you want to fix it crashing on launch for now, you can delete your config file or project file. Let me know if deleting either of those works for you (they should).

**Comment by humam2104** [comment] 2023-01-08 20:49
I will. But you sould know that sid I placed the dll file in the Game\ directory and still got errors.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by redsn0www** [comment] 2023-01-22 05:17
hey, i'm having issues with this as well. event is as listed:


Application: DSMapStudio.exe
CoreCLR Version: 6.0.1322.58009
.NET Version: 6.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: No physical devices exist.
   at Veldrid.Vk.VkGraphicsDevice.CreatePhysicalDevice() in D:\a\DSMapStudio\DSMapStudio\Veldrid\Vk\VkGraphicsDevice.cs:line 645
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions) in D:\a\DSMapStudio\DSMapStudio\Veldrid\Vk\VkGraphicsDevice.cs:line 127
   at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription, VulkanDeviceOptions vkOptions) in D:\a\DSMapStudio\DSMapStudio\Veldrid\GraphicsDevice.cs:line 853
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 189
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 173
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 105
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 40
   at StudioCore.MapStudioNew..ctor() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 110
   at DSMapStudio.Program.Main(String[] args)

**Comment by kingborehaha** [comment] 2023-01-22 21:37
> hey, i'm having issues with this as well. event is as listed
> 
> thanks for the help, i'm _fairly_ sure that the 3050 laptop GPU supports vulkan, as per their website
> 
> Application: DSMapStudio.exe CoreCLR Version: 6.0.1322.58009 .NET Version: 6.0.13 Description: The process was terminated due to an unhandled exception. Exception Info: System.InvalidOperationException: No physical devices exist. at Veldrid.Vk.VkGraphicsDevice.CreatePhysicalDevice() in D:\a\DSMapStudio\DSMapStudio\Veldrid\Vk\VkGraphicsDevice.cs:line 645 at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions) in D:\a\DSMapStudio\DSMapStudio\Veldrid\Vk\VkGraphicsDevice.cs:line 127 at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription, VulkanDeviceOptions vkOptions) in D:\a\DSMapStudio\DSMapStudio\Veldrid\GraphicsDevice.cs:line 853 at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 189 at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 173 at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 105 at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd) in D:\a\DSMapStudio\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 40 at StudioCore.MapStudioNew..ctor() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 110 at DSMapStudio.Program.Main(String[] args)

This is (another) an entirely different issue, which you can fix by disabling your onboard graphics in the device manager (DSMapStudio has trouble deciding which device is the best one to use).

**Comment by kingborehaha** [comment] 2023-01-22 21:39
Gonna close this now. 

@humam2104, if reinstalling the game as I suggested didn't fix the issue, open another issue report.

**Closed by kingborehaha** 2023-01-22 21:39 UTC

**Comment by humam2104** [comment] 2023-02-24 21:37
I can confirm that by reinstalling the game.. the program worked. Thanks anyways
